[package]
name = "red4ext-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[[example]]
name = "exports"
crate-type = ["cdylib"]

[dependencies]
cxx = "1.0"
autocxx = "0.13"
ctor = "0.1"
array-init = "2.0"
erasable = "1.2"
red4ext-rs-macros = { git = "https://github.com/jac3km4/red4ext-rs-macros", rev = "b1db321" }

[build-dependencies]
autocxx-build = "0.13"
