[package]
name = "red4ext-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[[example]]
name = "example"
crate-type = ["cdylib"]

[dependencies]
cxx = "1.0"
autocxx = "0.15"
array-init = "2.0"
erasable = "1.2"
wchar = "0.11"
casey = "0.3"

[build-dependencies]
autocxx-build = "0.14"
