name: Update

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Update submodules
      run: git submodule update --init --recursive
