name: Update

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Create commits
      run: |
        git config user.name 'Github Actions'
        git config user.email 'noreply@github.com'
        git commit -m "Update submodules"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: Update Submodules
        branch: github-actions-update-submodules
